### PR TITLE
Develop/fix frame branding

### LINKED ISSUE #57: Have video match Hyper's branding/style
Following recommendation from @rauchg, the recording output should match the branding of Hyper, as seen on the official website as such: 

Hyper Branding

I'm planning to do some work on getting the frame code cleaned up and matching this example. Any other suggestions are welcome!

### PR DESCRIPTION
**Pull request by rioam2**
Fixes #57. Adds Hyper branding to the recording frame by using correct colors and including the Hyper Logo. List of modifications:

 - Extracted HTML markup for frame into own file for ability to hotswap frames/themes later.
 - Made Frame responsive to current terminal font size (larger font size in Preferences -> larger frame size)
 - Maintain centering of window in logical view of video independent of frame size (larger frame pushes content down)
 - Corrected shadow being drawn after frame painting.
 - Moved variable declarations closer to lines of usage in startRecording

example

Please check out the changes and let me know if anything's not behaving as it should :)

### CODE REVIEW

File: recording.js [hunk 1]
```diff
@@ -57,82 +64,68 @@ function generateFrame(width, height, padding) {
...
+  baseCtx.shadowColor = 'rgba(0, 0, 0, 0.25)';
+  baseCtx.shadowBlur = width / 10;
+  baseCtx.fillStyle = backgroundColor;
+  baseCtx.fillRect(padding, padding + frameSize, width, height - frameRadius);
+
+  /* Paint Frame onto Canvas */
   return html2canvas(document.getElementById('orama-frame'), {
-    canvas: baseCanvas,
-    height: height + padding * 2,
+    backgroundColor: null,
```
Comment (kmui2) [inline recording.js:99]: Why is setting backgroundColor to null needed?

Comment (rioam2) [reply recording.js:99]: This is done for overlaying the HTML elements with a transparent background as seen in the [html2canvas documentation](https://html2canvas.hertzen.com/configuration). I agree that it's a poor API choice.

File: recording.js [hunk 2]
```diff
@@ -152,75 +145,85 @@ exports.startRecording = function(canvases, fileName) {
...
-    merger.addStream(cursorStream, {
-      x: framePadding,
-      y: framePadding,
-      width,
-      height,
-      mute: true,
-    });
+  /* Setup recording frame */
+  const { fontSize } = window.store.getState().ui;
+  const frameSize = fontSize * 6;
```
Comment (cwlowder) [inline recording.js:155]: Why is this related to the font size? Larger font=larger frame?

Comment (rioam2) [reply recording.js:155]: I did this to avoid situations where the terminal text is super small, but the frame's title bar is giant (like in the README.md example). Let me know if you'd like this to be handled differently 👍

Comment (cwlowder) [reply recording.js:155]: oh ok. Makes sense

**Review by cwlowder — APPROVED** [review]

File: recording.js [hunk 3]
```diff
@@ -35,16 +35,23 @@ function save(fileName, data) {
...
-
+function generateFrame(width, height, padding, frameSize, frameRadius) {
+  const { backgroundColor } = window.store.getState().ui;
+
+  /* Import frame markup and hyper logo */
+  const frameMarkup = fs.readFileSync(
+    path.join(__dirname, 'frame-markup.html'),
+    'utf-8',
+  );
+  const hyperLogoSVG = fs.readFileSync(
```
Comment (kmui2) [inline recording.js:49]: Could these two files be read in parallel?

File: recording.js (hunk 2 above)
Comment (lpulley) [reply recording.js:155]: This is a great addition. Didn't even realize such a feature would be possible the way you implemented it. Way to go man 👍

**Review by lpulley — APPROVED** [review]
This is slick. Don't have time to test today but looking at your code it seems fine. I assume you have this working on your Windows?

File: recording.js (hunk 3 above)
Comment (rioam2) [reply recording.js:49]: That’s a good call. Although these files are small, if you’d like to add parallel/async reading that would be awesome!

Comment (kmui2) [reply recording.js:49]: I think it's fine for now. We can come back to this when it's a bigger deal.

**Review by kmui2 — APPROVED** [review]
