### PR TITLE
Fixed issue where plugin does not load on a production version of hyper

### LINKED ISSUE #54: Hyper-Orama failing to run on production hyper
As opposed to a local dev instance of hyper, when using the hyper installed from https://hyper.is/, you get the following message on start:
```
[Notification] Plugin error!: Plugin "hyper-orama" failed to load (Unexpected token ...)
C:\Users\Pita\.hyper_plugins\local\hyper-orama\index.js:58
          this.setState({ ...this.state, canvases });
                          ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function._load (C:\Users\Pita\AppData\Local\hyper\app-2.1.2\resources\app.asar\plugins.js:77:29)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
Disabling Chromium GPU blacklist
running in prod mode
electron will open file://C:\Users\Pita\AppData\Local\hyper\app-2.1.2\resources\app.asar\index.html
Hyper CLI already in PATH
Hyper CLI installed You may need to restart your computer to complete this installation process.
[Notification] Plugin error!: Plugin "hyper-orama" failed to load (Unexpected token ...)
Checking for notification messages
No matching notification messages
```

### PR DESCRIPTION
**Pull request by cwlowder**
Fixes #54 
The issue has to do with hyper not liking the ... operator. Also, my version of hyper had 4 canvases, which failed due to us only reading in the first 3 canvases. I think we should look into a version of canvas recording that is more adaptable to any number of canvases.

### CODE REVIEW

**Comment by cjoshmartin** [comment]
@cwlowder Have you made any improvements yet?

File: index.js [hunk 1]
```diff
@@ -50,12 +50,9 @@ exports.decorateTerms = (Terms, { React }) => {
...
         if (canvasCollection.length >= 3) {
           const canvases = new Array();
-          document.body.removeEventListener(
-            'DOMSubtreeModified',
-            canvasListener,
-          );
+
           for (let canvas of canvasCollection) canvases.push(canvas);
-          this.setState({ ...this.state, canvases });
+          this.setState({ canvases });
```
Comment (cjoshmartin) [inline index.js:55]: Try this:
```suggestion
          this.setState(prevState, _ ) => ({...prevState, canvases }) );
```
 I think React doesn't like it when you spread `this.state` inside of `setState`. I think when you do so it throws the app into an infinite loop (maybe?)

Comment (rioam2) [inline index.js:55]: The spread operator is used correctly in the original code assuming ES6 standards (which I believe production version of Hyper is on ES5). Object.assign() is a fallback for the spread operator.
Merging your suggestion, Josh, with the original:
```suggestion
          this.setState((prevState, _) => Object.assign({}, prevState, {canvases}));
```

Comment (cwlowder) [reply index.js:55]: I think @TejasQ Once told me that updating the state this way with ... was not a good idea and it was unnecessary. That setState only updated the state and it wasn't necessary to explicitly include the old state.

Comment (cjoshmartin) [reply index.js:55]: Okay That makes sense

**Review by cjoshmartin — APPROVED** [review]
If this the only change then I approve.

**Review by rioam2 — APPROVED** [review]
I'm not able to test the changes on my machine right now, but I approve the changes based off of theoretical speculation 👍
